name: C Makefile Github Actions test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
    - uses: actions/checkout@v3
    - name: Compile the project
      run: make
    - name: Clean
      run: make clean
    - name: Clean and compile
      run: make re
